-- 코드를 입력하세요
-- 저자(AUTHOR) 별, 카테고리(BOOK) 별, 매출액 (BOOK, BOOK_SALES) 구하기 
-- AUTHOR_ID, AUTHOR_NAME,(AUTHOR) | CATEGORY,(BOOK) | SALES (BOOK, BOOK_SALES)
-- 정렬: AUTHOR_ID ASC, CATEGORY DESC
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES * B.PRICE) AS TOTAL_SALES
    FROM (SELECT BOOK_ID, SALES
            FROM BOOK_SALES
            WHERE MONTH(SALES_DATE) = "01") A
                LEFT JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
                LEFT JOIN AUTHOR C ON B.AUTHOR_ID = C.AUTHOR_ID 
    GROUP BY 1, 3
    ORDER BY 1, 3 DESC;