-- 코드를 입력하세요
WITH 
TMP AS (
    SELECT CAR_ID,
            CASE WHEN "2022-10-16" BETWEEN START_DATE AND END_DATE THEN 1
            ELSE 0 END AS IS_AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
    SELECT CAR_ID,
            CASE WHEN SUM(IS_AVAILABILITY) > 0 THEN '대여중'
            ELSE '대여 가능' END AS AVAILABILITY
        FROM TMP
        GROUP BY 1
        ORDER BY 1 DESC; 