-- 코드를 입력하세요
-- 생산일자 (FOOD_ORDER.PRODUCE_DATE)가 2022년 5월인 식품
-- PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES(PRICE * 주문수)
-- 정렬: TOTAL_SALES DESC, PRODUCT_ID 
SELECT A.PRODUCT_ID, PRODUCT_NAME, TOTAL_AMOUNT * PRICE AS TOTAL_SALES
    FROM FOOD_PRODUCT A, (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
                            FROM FOOD_ORDER
                            WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = "2022-05"
                            GROUP BY PRODUCT_ID) B
    WHERE A.PRODUCT_ID = B.PRODUCT_ID 
    ORDER BY 3 DESC, 1;