-- 코드를 입력하세요
-- 보호 시작일(ANIMAL_INS.DATETIME) > 입양일(ANIMAL_OUTS.DATETIME) 
-- 출력 컬럼: ANIMAL_ID, NAME
-- 정렬: ANIMAL_INS.DATETIME ASC

SELECT ANIMAL_ID, NAME, DATETIME
    FROM ANIMAL_INS I
    WHERE EXISTS (SELECT 1
                    FROM ANIMAL_OUTS O
                    WHERE I.DATETIME > O.DATETIME)
    ORDER BY DATETIME; 
    

SELECT I.ANIMAL_ID, I.NAME
    FROM ANIMAL_INS I, ANIMAL_OUTS O
    WHERE I.ANIMAL_ID = O.ANIMAL_ID
            AND I.DATETIME > O.DATETIME
    ORDER BY I.DATETIME; 