-- 코드를 입력하세요
SELECT MONTH(START_DATE), CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE CAR_ID IN (SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                        GROUP BY 1
                        HAVING COUNT(CAR_ID) >= 5)
            AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY 1, 2 
    ORDER BY 1, 2 DESC;
    
    
